### ISSUE TITLE
Remove GitHub Pages coupling

### ISSUE THREAD

**Issue by Weishaupt** [sproogen/modern-resume-theme#100]
**Is your feature request related to a problem? Please describe.**
I'd like to deploy to a different platform than GitHub pages. Currently the gem requires me to bundle all gh-pages requirements.

**Describe the solution you'd like**
I'd like this theme to lift the gh-pages requirement to be able to easily deploy to other platforms.

**Describe alternatives you've considered**
Deploying to another platform with all the unnecessary dependencies.

**Comment by sproogen** [comment]
At the minute I'm not sure if this is something I want to do as the main target for this is to create easily deployable sites on github pages. I will try and investigate if this is possible to do without needing to use github pages but I don't have too much time for this.

If you want to raise a PR for this that would be helpful.
