### ISSUE TITLE
Could I hide the projects section or change it as another name

### ISSUE THREAD

**Issue by dingjianyun830** [sproogen/modern-resume-theme#107]
I just used this template to create my CV. It is great. But I want to add the section such as publication.
And, I want to adjust the location between each section.

**Comment by jtilles** [comment]
You can just make the `projects.yml` file blank and it will be omitted.  I commented everything out 'projects.yml', and the project section no longer shows up in my resume.

**Comment by estefafdez** [comment]
I understand your point @jtilles but if you want to create a new section, is there any way? thanks!

**Comment by mabhijithn** [comment]
Yes. I have created a publications section. The website can be found [here](https://abhimundanad.com/). The changes I made can be seen in this [forked repo](https://github.com/mabhijithn/modern-resume-theme).

**Comment by sproogen** [comment]
Hi, I know this has been here for a little while, but I have just raised a PR(#117) for a config version v2. I've been thinking about it for a while and finally found the time, it should allow you to fully customise create/remove/order the content sections without making code changes. I am hoping to merge this soon and also add some different content sections layouts soon too.
Hopefully this will do what you need.
