### ISSUE TITLE
Unable to change about_profile_image

### ISSUE THREAD

**Issue by QuocViNguyen** [sproogen/modern-resume-theme#111]
**Linking profile picture in config.yml not working**
Hi, thank you for providing such a great template. I use it to generate my online resume, but I stop at changing my own About profile picture. Basically, I created a new folder "images" and put my picture in there, and I went on to modify the config.yml. Please see the screenshots attached for better visualization. 
<img width="1306" alt="Screen Shot 2020-10-29 at 02 13 42" src="https://user-images.githubusercontent.com/59320270/97537187-67a64d80-198c-11eb-9dd9-7bdda32815df.png">

Also, I when on and check the about.html in _includes folder, VSCode warns me of some errors which I attached a picture to explain: 
<img width="1440" alt="Screen Shot 2020-10-29 at 02 15 54" src="https://user-images.githubusercontent.com/59320270/97537361-b2c06080-198c-11eb-8101-f3e72ba6fac0.png">

**Expected behaviour**
I really expect it to work as a demo. But this is what I got so far:
<img width="1440" alt="Screen Shot 2020-10-29 at 02 17 22" src="https://user-images.githubusercontent.com/59320270/97537524-ebf8d080-198c-11eb-9d90-8a21e31f0032.png">

FYI, I'm using Macbook Pro 2018 Catalina.

**Comment by QuocViNguyen** [comment]
Apparently, I have to rebuild the website again for my image to work. It is fixed now, but I am still curious about the problem messages in about.html.

**Comment by asarraf** [comment]
@QuocViNguyen : Can you mark this as closed since you were able to figure out the solution.
