### ISSUE TITLE
Add media section to the projects and/or experience sections

### ISSUE THREAD

**Issue by MArndt26** [sproogen/modern-resume-theme#112]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Be able to add media (pictures or videos) to the project or experience sections of the resume.  The user would be able to go into projects.yml and change an optional field for a list of photos.  Example: add a photos fields and the user would enter in ./assets/my_media.jpeg.  The end result would be that the resume website would have a picture under the description of the project which would help spice up the interface.

it would look something like this:
# Project template
- layout: top-middle
  name: name of project
  link: link to project
  github: Github page for project (eg. sproogen/modern-resume-theme)(optional)
  quote: >
    quote goes here
  description: | # this will include new lines to allow paragraphs
    long form description of project
  photos:
    - photo: ./assets/my_photo.jpeg
      photo_caption: here is a caption of the photo
  videos:
    - video: ./assets/my_video.mp4
      video_caption: here is a caption for the video

**Describe alternatives you've considered**
NA

**Additional context**
I have attempted to do this myself with photo, photo_caption, video, video_caption fields however I am very new with web design so I'm excited to see what you could do to spice things up (autoplay, fun animations, etc...)

**Comment by sproogen** [comment]
I'm not sure if you have managed to figure out a way of doing this, but as the description field of each item uses markdown you can add images directly using `![alt text](./assets/my_photo.jpeg)`

**Comment by MArndt26** [comment]
Thanks for the response.  I tried that for a first attempt but found that formatting the photos wasn't too easy.  Instead, I found some helpful .HTML /css to get a fun "photo gallery" (see below) and/or video gallery:

![image](https://user-images.githubusercontent.com/49196241/99885899-35dc7b80-2c06-11eb-96b6-3398db77bc59.png)


I did this by modifying projects.html to the following:
```
<div class="container projects-container">
	<h3>{{ site.projects_title | default: "Projects" }}</h3>
  	{% for project in site.data.projects %}
		{% include {{ project.layout | default: 'left' | append: ".html" }} item=project %}
		<div class="media-container">
			{% if (project.photos) %}
			<h1>Photo Gallery</h1>
			{% endif %}
			<div class="photo-grid">
				{% for photo in project.photos %}
					<div class="{{ photo.photo_type }}" style="background-image: url('{{ photo.photo }}')"></div>
				{% endfor %}

			</div>
			{% if (project.videos) %}
			<h1>Video Gallery</h1>
			{% endif %}
			{% for video in project.videos %}
				<div class="video-responsive">
					<iframe width="560" height="315" src="{{ video.video }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
				</div> 
				<p>{{ video.video_title }}</p>
			{% endfor %}
		</div>
	{% endfor %}
</div>
```


I also added some css:

```
.media-container {
  margin-top: 2rem;
  h1 {
    font-size: 30px;
  }
  p {
    text-align: center;
  }
  img {
    height: 10vh;
    margin: auto;
    display: block;
  }
  video {
    max-width: 100%;
    height: 75vh;
    margin: auto;
    display: block;
  }
}

.video-responsive {
  overflow: hidden;
  padding-bottom: 56.25%;
  position: relative;
  height: 0;

  iframe {
    left: 0;
    top: 0;
    height: 100%;
    width: 100%;
    position: absolute;
  }
}

.card {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background: #353535;
  font-size: 3rem;
  color: #fff;
  box-shadow: rgba(3, 8, 20, 0.1) 0px 0.15rem 0.5rem,
    rgba(2, 8, 20, 0.1) 0px 0.075rem 0.175rem;
  height: 100%;
  width: 100%;
  border-radius: 4px;
  transition: all 500ms;
  overflow: hidden;

  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
}

.card:hover {
  box-shadow: rgba(2, 8, 20, 0.1) 0px 0.35em 1.175em,
    rgba(2, 8, 20, 0.08) 0px 0.175em 0.5em;
  transform: translateY(-3px) scale(1.1);
}

.photo-grid {
  display: grid;
  gap: 1rem;

  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  grid-auto-rows: 240px;
}

/* Medium screens */
@media screen and (min-width: 600px) {
  .card-tall {
    grid-row: span 2 / auto;
  }

  .card-wide {
    grid-column: span 2 / auto;
  }

  .card-big {
    grid-row: span 2 / auto;
    grid-column: span 2 / auto;
  }
}

```

The way to add photos, you would go into projects.yml and add code in the following format directly after the description section of a project:
```
photos:
    - photo: ./assets/project.png
      photo_title: this is the description
      photo_type: card card-wide
    - photo: ./assets/project.png
      photo_title:  this is the description
      photo_type: card
```
you can add as many photos by repeating this format.

for photo_type, you can choose any combination of card, card-wide, card-tall, or card-big for setting the proportions of the
photo in the grid.

To add videos, you would add a similar section to projects.yml:
```
videos:
    - video: https://www.youtube.com/embed/q_7Y24A6oFY
      video_title: AMP Electrical Full Integration
    - video: https://www.youtube.com/embed/q_7Y24A6oFY
      video_title: AMP Electrical Full Integration
```
An important note here is to use the embedded youtube video address.  Also, this only works for adding youtube videos currently, although you could easily change the HTML to use a local video.

**Comment by sproogen** [comment]
I think my feeling at the minute is that I don't want to add anything like this into this project. The main goal of this was to have an online version of a paper CV that provides a universal layout out the box in a way that can be printed too. I think this goes a little bit past that and into the online portfolio territory.
It's open source so I'm completely happy for people to add things like this to their own version, and really like to see it too, but I think I want to keep the core project as simple as possible.
