### ISSUE TITLE
Swap/Move Sections

### ISSUE THREAD

**Issue by lizruonan** [sproogen/modern-resume-theme#113]
Hi, thank you for making this template! I want to swap between sections or move a section, e.g. move Educations to the top. I am new to this and have no idea how... Thank you :)

**Comment by sproogen** [comment]
Hi, thanks for raising this. Something I had been thinking about for a while was making everything more configurable without needing to edit the code. I have just put up a PR (#117) for a new way of defining content that will let you create/order/remove content sections to make it how you want. I should be merging this shortly. Hopefully this will be helpful for you.
