### ISSUE TITLE
can't build page

### ISSUE THREAD

**Issue by balazssandor** [sproogen/modern-resume-theme#121]
Your SCSS file modern-resume-theme-gh-pages/assets/main.scss has an error on line 1: File to import not found or unreadable: modern-resume-theme. Load path: /hoosegow/.bundle/ruby/2.7.0/gems/jekyll-theme-primer-0.5.4/_sass.

**Comment by smadnani** [comment]
Hey how did you solve this? I am getting the same error on line 1.

**Comment by balazssandor** [comment]
Check my profile and you will see the repo.
