### ISSUE TITLE
Livereload is not supported

### ISSUE THREAD

**Issue by pourmand1376** [sproogen/modern-resume-theme#142]
I've tested lots of templates for Jekyll out there and I found your template which is awesome. The only drawback is that live reload feature doesn't work with your template. 

Can you tell me how to fix this problem? I've searched many forums and stackexchange site and yet haven't found a solution.

**Comment by sproogen** [comment]
Unfotunately this is how Jekyll works, as the config.yml file is key to what Jekyll builds. There are solutions such as using watchy you can find here https://github.com/jekyll/jekyll/issues/2302#issuecomment-53972523
