### ISSUE TITLE
Add skills section

### ISSUE THREAD

**Issue by Haki-Malai** [sproogen/modern-resume-theme#145]
**Is your feature request related to a problem? Please describe.**
There is no way in how to show your skills. With this extention i can add a skill section that has bars for each skill filled on how good the user is on the skill noted.

**Describe the solution you'd like**
The data is read from the _config.yml file (new content -> skill for which will be added html files) and with the use of javascript the bar get filled. For example: for python skill 7/10 the bar get filled respectively.

**Describe alternatives you've considered**
Css icons instead of letters.

**Additional context**
Here is an example on the final product, which im currently using in my own [cv](https://haki-malai.github.io/cv/)
<img src="https://i.ibb.co/hL2sCP2/Screenshot-3.png" alt="Screenshot-3" border="0">

**Comment by sproogen** [comment]
Thanks for raising this, I do have a card for this in the Project Backlog board here https://github.com/sproogen/modern-resume-theme/projects/1#card-50180122 If you keep an eye there for any updates on this.

**Comment by Haki-Malai** [comment]
I would like to contribute on this, how may i help?
