### ISSUE TITLE
How to make some custom changes about font (such as size or type)

### ISSUE THREAD

**Issue by hxwork** [sproogen/modern-resume-theme#148]
Hello,

Thanks for your template, I want to change the default font of section content, such as increasing the font size or line space, but I don't know how to make it. I have tried to use markdown commands, however, the result is not satisfying.
```
<font size="2"> This is my text number 2 </font>
```
This solution may be helpful, but I can not insert links into it, for example,
```
<font size="2"> This is my text number [link](https://www.google.com) </font>
```
"font" will make "link" not work. Which part should I modify to achieve the goal?

**Comment by sproogen** [comment]
I don't think markdown supports adding videos, and it's not very common that a video would be included in a resume. You would probably be better off just adding a link to the video hosted on another platform.

**Comment by hxwork** [comment]
Thanks for your reply. I am not asking about using markdown, but anyway, I have solved the problem.
