### ISSUE TITLE
Error in Build

### ISSUE THREAD

**Issue by mumesh10** [sproogen/modern-resume-theme#180]
**Describe the bug**

**To Reproduce**
1. Go to 'Actions'
2. Click on 'Build'
3. Scroll down to 'Build with jekyll'

**Expected behavior**
whichever is the first line of config file, it is shown as that line is the errror

**Screenshots**
![image](https://user-images.githubusercontent.com/108412495/209419849-2fb2f1f6-e38c-46ef-b3db-cf6a1ba5ed9a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 108

**Comment by nhnduy** [comment]
Hello, I got the same issue. Did you figure out how to fix it? Please let me know. Thank you.

**Comment by mumesh10** [comment]
I couldn't figure out the error. So I used another repo for building a website. Not with Jekyll

**Comment by raleighlittles** [comment]
> I couldn't figure out the error. So I used another repo for building a website. Not with Jekyll

What repository did you use?

**Comment by ChrisGoettfert** [comment]
any updates on this one?

**Comment by mumesh10** [comment]
> > I couldn't figure out the error. So I used another repo for building a website. Not with Jekyll
> 
> What repository did you use?

This was the repository I used: https://github.com/academicpages/academicpages.github.io

**Comment by mumesh10** [comment]
> any updates on this one?

I couldn't figure out the error with but I used another repository: https://github.com/academicpages/academicpages.github.io
