### ISSUE TITLE
Make More Content option

### ISSUE THREAD

**Issue by davidsivocha** [sproogen/modern-resume-theme#28]
**Is your feature request related to a problem? Please describe.**
At the moment the More Content section is non optional and the title always appears requiring it to be filled. More Content should be optional and at the users discretion. 

**Describe the solution you'd like**
If more content is nil, or commented out it should not display the more content section

**Describe alternatives you've considered**
I don't see any alternatives to this solution.

**Additional context**
Empty More Content shows as below
![screenshot 2018-12-02 at 12 20 53](https://user-images.githubusercontent.com/822774/49336662-bcb87800-f62c-11e8-9c9d-55d163fd2d67.png)

**Comment by davidsivocha** [comment]
I've provided a PR for this. You can see PR #29 for details.

**Comment by sproogen** [comment]
Awesome, thanks for this. I hadn't considered people not wanting the more content section.

Merged your PR
