### ISSUE TITLE
Changes in config.yml doesn't reflect locally but works when pushed to github

### ISSUE THREAD

**Issue by shreyas707** [sproogen/modern-resume-theme#47]
**Describe the bug**
First of all, thank you so much for creating such a nice theme for free. :)

When I change the description of About Me in config.yml and run it locally, the changes don't get reflected. But if I push it to Github, I see all the changes. 
It happens only with config.yml file. Education, experience and projects work fine. 

**To Reproduce**
1. Run the server locally
2. Edit the About Me part in config.yml
3. The changes don't get reflected locally
4. Push the code to github
5. You can see the changes getting reflected on the website

**Expected behavior**
I expected the changes made in config.yml to reflect locally.

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave 10.14.3
 - Browser: Google Chrome
 - Version: 72.0.3626.121 (Official Build) (64-bit)

**Additional context**
Ruby version: 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
Jekyll version: 3.7.4

Let me know if any other information is required

**Comment by sproogen** [comment]
Have you restarted Jekyll locally? As config.yml contains app config it will only be read when the app is first started. You will need to re-run `bundle exec jekyll serve` to see changes made in `_config.yml`. 

Unfortunately this is just how jekyll works and not something I can control.

**Comment by shreyas707** [comment]
Oh! I feel so dumb right now. Restarting Jekyll helped. Thanks!
