### ISSUE TITLE
Projects link stick out into description

### ISSUE THREAD

**Issue by pouyan9675** [sproogen/modern-resume-theme#48]
**Projects link stick out into the description**
When projects link in the projects section is too long the link sticks out into the description. Is there any way to solve this problem? because it really feels unpleasant.
Thank you

**Comment by sproogen** [comment]
I am currently looking at creating a couple of different layouts for projects which should allow it to support different longer links and content.

In the mean time you can copy/modify the file 'assets/main.scss' and add some overrides to the styles to make the link wrap.

**Comment by pouyan9675** [comment]
Thank you for your reply. It solved my problem.

**Comment by pouyan9675** [comment]
Thank you for your reply. It solved my problem.
