### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by M-Razavi** [sproogen/modern-resume-theme#52]
I'm thinking about a navigation bar on top of the resume.

something like https://belgoros.github.io/ or https://suddi.io/

**Comment by sproogen** [comment]
I'm not really sure what you are saying here.

I don't think a navigation bar would fit with the single page site I am going for.

But feel free to extend the project for your own resume if you would like to add a navigation bar.

**Comment by M-Razavi** [comment]
Ok Thanks
