### ISSUE TITLE
Dark mode + child pages

### ISSUE THREAD

**Issue by jeremych1000** [sproogen/modern-resume-theme#54]
Hey - great template, thanks for sharing.

Two questions though.

1. Is there possibility to change the colours? I would love a dark mode version!
2. I see `_layouts/default.html`, and `_data`. How do I make child pages that follow the same template? The instructions are great for editing the main page, but I would love some guidance on how to make custom sections under child pages like `https://<domain>/<child_page>`

**Comment by sproogen** [comment]
Thanks,

At the minute there is no specific way to change colours, but you can add any styles you want to `assets/main.scss` and override anything you want to change colour. But it's something I have considered in the future to have colours as an option in the config.

Also this is designed as a complete single page app. But I think you would be able to make another page in the root directory `child_page.md` (or .html). You will be able to read up on this a bit more in Jekylls documentation https://jekyllrb.com/docs/structure/
