### ISSUE TITLE
Ability to change _config.yml or another file without restarting jekyll (docker)

### ISSUE THREAD

**Issue by ageisen2000** [sproogen/modern-resume-theme#55]
**Is your feature request related to a problem? Please describe.**
I've been running this website in a docker container and it is a little tedious to restart the container every time I want to make changes.

Is there an easy way to automatically regenerate or rebuild based on _config.yml changes? 

Something as simple as a script that will automatically rebuild the entire website on _config.yml changes would make a huge difference for docker users.

**Comment by sproogen** [comment]
Unfortunately this is just the way Jekyll works, any changes to _config.yml and it would has to be restarted. I guess it would be possible to write a script to handle the running of Jekyll but not something I have the time to do right now. 
There might possibly be a script someone else has already written but I'm not sure.
Sorry.

**Comment by sproogen** [comment]
There is a good suggestion of using watchy here https://github.com/jekyll/jekyll/issues/2302#issuecomment-53972523

**Comment by sproogen** [comment]
Closing this issue as a possible solution was given above.
