### ISSUE TITLE
Creating a new part

### ISSUE THREAD

**Issue by EhsanMashhadi** [sproogen/modern-resume-theme#58]
Hi,
Is there any way to create a new part like Skills or Selected Courses?

**Comment by sproogen** [comment]
You can update the _layouts/default.html template and add a new section, then copy the config from one of the existing sections and rename them.

In the future I am looking at making the content completely flexible, so you would be able to add as many different sections with different names as you want.

**Comment by EhsanMashhadi** [comment]
Thanks
