### ISSUE TITLE
Font Awesome & dark mode

### ISSUE THREAD

**Issue by mrufflesmcghie** [sproogen/modern-resume-theme#62]
**Is your feature request related to a problem? Please describe.**

Absolutely love this theme, after attempting to add Discord icon had issues with Font Awesome. 
Add the option in config.yml and also updated Font Awesome to latest version using Bootstrap CDN and updated other icons to new naming. 
Would you like a pull request for this, I see their is a shim for this if that's better

I'm new to using git and developing websites etc 

I'm also planning on working on a dark mode, would this be something of interest? 

Thanks in Advance n hope that all makes sense.

**Comment by sproogen** [comment]
Yea a PR to update the font awesome would be great.

A dark mode is something I had been considering too, I was thinking about possibly using this https://watercss.netlify.com/ which already as a dark/light mode toggle.

Thanks

**Comment by mrufflesmcghie** [comment]
Not sure if you have seen but check out my 1st attempt at dark mode with just css and javascript.
[https://mrufflesmcghie.github.io/resume/](https://mrufflesmcghie.github.io/resume/)
I checked out watercss but not too convinced, however it's easier to implement its easier to add custom colours etc when using scss already included in jekyll.

**Comment by sproogen** [comment]
I had a look at what you had done in your resume, and I do really like that annalytic demo.

I know it's also possible to recognise the users device dark mode preference, so that is also something I am going to look into. But I think going the direction of the annalytic demo is a good idea.

I will probably be able to find some time over the weekend to look into it unless you wanted to take a look first.

**Comment by mrufflesmcghie** [comment]
Was reading about that too, simplely adding a JS in the head detects users preference.
My first assignment is finally done so will have some time this evening and weekend to work on this. 
I have also been looking into #58 think I have found a way using order in the front matter but may need a bigger overhaul to layouts & templates. 

Need to also figure out all the building processes etc etc as can't seem to get remote theme @ branch working :-(

**Comment by mrufflesmcghie** [comment]
https://github.com/mmistakes/minimal-mistakes/issues/1208
Use darkmode as user input switch, user pref. 
Keep other skins to config.yml for us to change if fancy

Let me know what you think, I want to incorporate a blog into my page for family's so going a bit beyond your requirements.

**Comment by bertrand-benoit** [comment]
Hi, thanks for your work!

I'm really interested in a Dark mode too; is there any news on it?

**Comment by mrufflesmcghie** [comment]
@bertrand-benoit at the moment Ive stopped Jekyll dev my side. I tried to add themes and easier way to manage content and kinda broke my fork.
Im was going to have another play tonight funny enough hard to fit in between projects.
@sproogen have you done anything since?

**Comment by mrufflesmcghie** [comment]
I can also attempt to open a PR maybe to a new branch (dark_mode) I've got the basic functionality just need someone with Java experience to fix the button n also use User preference.

**Comment by bertrand-benoit** [comment]
Yes create it please, I'll check.
Javascript you mean ?

**Comment by sproogen** [comment]
@bertrand-benoit @mrufflesmcghie I had been looking at this again recently. Just put up a PR with an implementation that is configured in the config,yml. https://github.com/sproogen/modern-resume-theme/pull/73

I'm don't really think the user needs to have the option to toggle it, but I might add something that detects if the user has dark mode turned on on their device and set it that way too.

**Comment by bertrand-benoit** [comment]
I worked on my new resume to eventually provide a simple Dark/Light theme switcher, based on what I've found on Internet + some of links here + some of your work on your branch.

Later, I may provide a PR if you want.

Don't hesitate to give me feedbacks: https://bertrand-benoit.github.io/

**Comment by sproogen** [comment]
I can take a look at your branch and pull anything over, it does looks good thought.

Might need an option to configure the colours in config, your dark mode is quite bold :joy:
