### ISSUE TITLE
certificates section

### ISSUE THREAD

**Issue by n0npax** [sproogen/modern-resume-theme#81]
It would be awesome to have section for certificates.

**Comment by mrufflesmcghie** [comment]
Currently playing around locally with an implementation, some suggestions for UI design would be nice :-D

**Comment by n0npax** [comment]
As a user I'd love to have a section for certificates where I can puts Images with hyperlinks. Sth like:
```
+--------------+
| C1 | C2 | C3 | 
+--------------+
| C4 | C5 | C6 | 
+--------------+
```

Alternatively, I'd be also happy to have section which is basically copy of projects(just different name), so I can pass html and css on my own.

Thanks @mrufflesmcghie

**Comment by wendelinwemhoener** [comment]
A copy of projects for certificates and things competitions etc. would really be great!

**Comment by garethtalty** [comment]
I started having a play with this on my forked repo.

Have a look and see if this is the sort of thing you're looking for: https://github.com/garethtalty/modern-resume-theme/pull/1

If @sproogen wants to go down this route then I will clean this up and create a PR. 

I know he has some ideas about making the sections more controllable via configuration, so I'm not sure if this is going in a direction that he wants to avoid

**Comment by sproogen** [comment]
Sorry it's taken so long to get around to it, but I finally decided on how I wanted this to work and now have a PR(#117) up with a config version v2. This will allow you to create/remove/order your content sections without changing the code. I'm hoping to get this merged shortly and then work on some different content sections layouts for things like skills or certificates.

Also the description sections support markdown, so you can create tables and anything else supported my markdown in these areas. 

If anyone want's to take a look at the PR or give me any suggestions after I've merged it that would be great.
