### ISSUE TITLE
Invalid theme folder: _sass

### ISSUE THREAD

**Issue by Conatuseus** [sproogen/modern-resume-theme#83]
hi.
first of all, thank you. 😄 
i have below error, but can't resolve for hours. (running locally)
could you help me?  :D 

![image](https://user-images.githubusercontent.com/22893111/71554071-bd088a00-2a5d-11ea-9053-e01bc7fc27ba.png)

<projects.yml>
![image](https://user-images.githubusercontent.com/22893111/71554499-3f477d00-2a63-11ea-82cb-b672560ad13c.png)

my resume repository is [here](https://github.com/Conatuseus/Conatuseus.github.io)

**Comment by mrufflesmcghie** [comment]
@Conatuseus did you run bundle install before attempting to serve ?

**Comment by Conatuseus** [comment]
@mrufflesmcghie 
yes, i did.
i did run below step in terminal.
~~~ terminal
bundle install
bundle exec jekyll serve
~~~

I just confirmed that there are _sass in `modern-resume-theme`, but i don't have.
so, Is that file required?

**Comment by Conatuseus** [comment]
> @mrufflesmcghie
> yes, i did.
> i did run below step in terminal.
> 
> ```
> bundle install
> bundle exec jekyll serve
> ```
> 
> I just confirmed that there are _sass in `modern-resume-theme`, but i don't have.
> so, Is that file required?

**Comment by sproogen** [comment]
Hi,

I'm on holiday atm, but will be able to take a look when I'm back in a
week. I don't think this issues is anything to do with the _sass folder,
looking at your screenshot the bottom 2 lines look like it is failing to
pass your projects.yml so I would start by looking there.

Regards

**Comment by sproogen** [comment]
A bit more research and it looks like it probably isn't an error on line 1 column 3, this is usually reported wrong. Try commenting out your projects.yml and un-comment a line at a time until you find the issue.

**Comment by Conatuseus** [comment]
@sproogen 

Hi 😄
Thank you for the answer.

i just was believe in error log `line 1 column 3`, so i can't find.
i saw your answer, comment all and un-commented line by line.
so. i can find answer.
The problem was the double quotes on the second line.

You made my day. 💯 👍
