### ISSUE TITLE
Add links

### ISSUE THREAD

**Issue by wendelinwemhoener** [sproogen/modern-resume-theme#85]
I would like to add custom links, for example to the experience column. However, this it not possible with normal markdown notation in the _date\experience file. What should I do? Could you please add the ability to include links in the text you write?

**Comment by sproogen** [comment]
I'm not sure what you mean? If you are writing a block of text you can add links using standard markdown.

Could you provide some more details on what, and how, you are trying to do?

**Comment by wendelinwemhoener** [comment]
I tried using standard markdown and it didn´t work.

This is the projects.yml file where I embedded a link with standard markdown syntax:
![image](https://user-images.githubusercontent.com/49584216/71841220-35ef8d80-30bf-11ea-8dec-979738d1865d.png)

However, this does not display the link correctly on the website:
![image](https://user-images.githubusercontent.com/49584216/71841302-60d9e180-30bf-11ea-96fd-130359435bdf.png)

Could you just tell me what I am doing wrong?
Thanks a lot in advance

**Comment by mrufflesmcghie** [comment]
@wendelinwemhoener I just visited your site and the links work just don't have any path.... Are the repos private your linking too?

**Comment by wendelinwemhoener** [comment]
I do not mean the link to my github repos but the link I´m trying to add in line 7 of the projects.yml file. The link to www.google.com doesn´t work.

**Comment by sproogen** [comment]
In the screenshot you added you have a space between [Google] and (www.google.com). There should be no space between these.

You can see the different ways markdown links can be formatted here https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links but you can't have any spaces between the labels and urls

**Comment by wendelinwemhoener** [comment]
Ups. You're right. Thank you so much!
