### ISSUE TITLE
Blog part

### ISSUE THREAD

**Issue by tvdsluijs** [sproogen/modern-resume-theme#88]
This is a great theme, looks and feels clean and fast. The only thing that would be great is a Blog part.

What I would like is a blog part! Then it would be complete.

Thank you and keep up the good work!

**Comment by sproogen** [comment]
Hi, thanks for the nice comments.

I have been staying away from adding a blog to this project atm to keep it simple.

You could pair this with another jekyll blog theme to achieve the same thing. I have seen some people use it like that before.
