### ISSUE TITLE
Add wordpress social link

### ISSUE THREAD

**Issue by ciehanski** [sproogen/modern-resume-theme#91]
**Is your feature request related to a problem? Please describe.**
I'd like to request an option for "Wordpress" to be added to the social links configuration options.

**Describe the solution you'd like**
An icon and config option similar to Twitter, GitHub, etc...

**Describe alternatives you've considered**
Adding the blog link elsewhere in the page.

**Additional context**
I have a Wordpress blog that I'd like to link from modern-resume-theme.

Awesome work, thanks so much!

**Comment by sproogen** [comment]
I decided recently that I do not want to keep defining the links that people can add as the list of options and code to support this would keep getting longer.

If you look in the _config.yml example you will see I have added the ability to define links yourself.  You can give the font-awesome icon name, a title and URL.
https://github.com/sproogen/modern-resume-theme/blob/master/_config.yml#L29

Hopefully this solves your issue.

**Comment by ciehanski** [comment]
Oh, fantastic! That solves it.
