### ISSUE TITLE
Some assistance please

### ISSUE THREAD

**Issue by djquazzi** [sproogen/modern-resume-theme#92]
Im new to Jekyll and YAML files.
I have got the resume working fine, however, I add anything to the `Projects Section,Experience Section,Education Section` it errors out. `You have an error on line 2 of your `_config.yml` file`
Im probably doing it wrong. Here is one of those sections:

```
# Projects Section
projects_title: Competencies
- layout: left
  name: Languages
  description: | # this will include new lines to allow paragraphs
    English
```

Any help would be appreciated

**Comment by sproogen** [comment]
Ah yes, I can see what is wrong.

So this bit in your _config.yml
```
- layout: left
  name: Languages
  description: | # this will include new lines to allow paragraphs
    English
```
should actually be placed in the `_data/projects.yml` file. The same would go for experience and education in separate yml files.

You can see an example of a project here https://github.com/sproogen/modern-resume-theme/blob/master/_data/projects.yml

And if you want to add multiple projects then you can add multiple like this https://github.com/sproogen/jameswgrant/blob/master/_data/projects.yml

**Comment by djquazzi** [comment]
Ah, yes. Thank you for your help. All good now
