### ISSUE TITLE
'darkmode: true' not working

### ISSUE THREAD

**Issue by jeremy-hicks** [sproogen/modern-resume-theme#93]
**Describe the bug**
Setting `darkmode: true` in _config.yml doesn't change page appearance/dark mode doesn't enable.

**To Reproduce**
1. Add `darkmode: true` in _config.yml.
2. Push changes.
3. Observe lack of dark mode.

**Expected behavior**
Dark mode is enabled when `darkmode: true` is set in _config.yml.

**Screenshots**
My page with `darkmode: true` set: [https://reysic.com](https://reysic.com)
Line in my _config.yml: [_config.yml](https://github.com/jeremy-hicks/jeremy-hicks.github.io/blob/3d564e72f38c64abde2c546afe3abfb0c4635f2d/_config.yml#L11)

**Comment by garethtalty** [comment]
`darkmode: true` works correctly if your client device is set to prefer a dark color scheme. 

How to enable this feature on your device depends on your device and operating system.

Navigating to https://reysic.com on my Android device (with One UI 1.0 and dark mode enabled) shows your resume with darkmode enabled:

![SmartSelect_20200315-132354_Samsung Internet](https://user-images.githubusercontent.com/1879096/76702279-7c192c80-66c0-11ea-9a1a-25c06e565b8c.jpg)

What device/operating system are you using? It should just be a case of enabling dark mode on your device to use this feature

**Comment by sproogen** [comment]
Setting `darkmode: true` is meant to override the check for the users browser preference and set the darkmode.

The issue here is that it looks like you have a overridden the default layout (`_layouts/default.html`) and it doesn't include the code for the darktheme preference.

If you haven't made any modifications to this file you can delete it and then it will use the most up to date one from the theme. Or you can update line 6 to this https://github.com/sproogen/modern-resume-theme/blob/master/_layouts/default.html#L6

**Comment by garethtalty** [comment]
@sproogen I think the `resume-template.zip` in Step 3 of the installation instructions may be out of date then: https://github.com/sproogen/modern-resume-theme#step-3---download-resume-template. 

`default.html` in here doesn't include `<body class="{% if site.darkmode %}dark{% endif %}">` so the override doesn't work, it just sets based on browser preference

**Comment by sproogen** [comment]
Looks like it's my fault then, that download automatically creates a zip of the current gh-pages branch. And I've overridden the default layout in that branch to add the github fork me banner 😂 

I will delete that `default.html` layout from the gh-pages branch now.

@jeremy-hicks you will still need to delete that layout branch from your theme for the dark mode to start working too.

**Comment by jeremy-hicks** [comment]
Thanks @garethtalty and @sproogen for your replies, deleting `default.html` resolved the issue.
