### ISSUE TITLE
darkmode: true obscures email address

### ISSUE THREAD

**Issue by garethtalty** [sproogen/modern-resume-theme#95]
**Describe the bug**
When `darkmode: true` is enabled, all elements are given a background color, meaning email contact info is obscured by the 'fork me on GitHub' banner at certain resolutions.

**To Reproduce**
1. Add darkmode: true to _config.yml
2. Navigate to the hosted resume in a browser with dark mode enabled
3. Reduce screen resolution to 1280px width
4. Observe obscured email contact details as per screen-grab below.

**Expected behavior**
Email contact info is displayed unobscured

**Screenshots**
![Screen Shot 2020-03-15 at 13 59 04](https://user-images.githubusercontent.com/1879096/76702943-a4eff080-66c5-11ea-9f96-6bd614bbe453.png)
![Screen Shot 2020-03-15 at 13 59 12](https://user-images.githubusercontent.com/1879096/76702946-a7eae100-66c5-11ea-851e-480ae0650c36.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Browser: chrome
 - Version 80.0

**Comment by sproogen** [comment]
I only added the forkme banner for the test repo, it's not meant be on everyone's resumes 😂  But it seems like a lot of people fork the main repo instead of the starting point codebase linked in the readme.

Removing the wildcard is probably the right thing anyways.
